SNP_Internship_Django/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.contrib.staticfiles.views import serve
from django.conf import settings
from django.conf.urls.static import static

from . import views

def return_static(request, path, insecure=True, **kwargs):
    return serve(request, path, insecure, **kwargs)

urlpatterns = [
    re_path(r'^static/(?P<path>.*)$', return_static, name='static'),
    path('', views.permanent_redirect, name='permanent_redirect'),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'polls.views.page_not_found'

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib import admin


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    @admin.display(boolean=True, ordering="pub_date", description="Published recently?")
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

SNP_Internship_Django/views.py
from django.http import HttpResponsePermanentRedirect

def permanent_redirect(request):
    return HttpResponsePermanentRedirect("/polls/")

polls/views.py
from django.db.models import F
from django.http import HttpResponseRedirect, HttpResponseNotFound
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:10]

class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        """
        Excludes any question that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

    def get_queryset(self):
        """
        Excludes any question that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "polls/detail.html", {
            "question": question,
            "error_message": "You didn't select a choice."
        })
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

def create(request):
    if request.method == "POST":
        new_question = Question()
        new_question.question_text = request.POST["title"]
        new_question.pub_date = timezone.now()
        new_question.save()

        for choice in request.POST.getlist("choice"):
            new_choice = Choice()
            new_choice.choice_text = choice
            new_choice.votes = 0
            new_choice.question = new_question
            new_choice.save()
        return redirect("polls:index")
    return render(request, "polls/create.html")


def page_not_found(request, exception):
    return render(request, "polls/404.html")

polls/templates/polls/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div>
    <h2 class="leftstr">Create new poll</h2>
    <h2 class="rightstr"><a href="{% url 'polls:index' %}">Go Home</a></h2>
</div>
<form action="{% url 'polls:create' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <input type="text" name="title" placeholder="Enter your poll" class="text-field__input"  required />
    </div>
    <ul id="optionsContainer">
        <li class="option-item">
            <div>
                <input type="text" name="choice" placeholder="Enter choice title" class="choice-text-field__input" required/>
                <button type="button" onclick="removeOption(this)" class="btn btn-danger">Remove</button>
            </div>
        </li>
    </ul>
    <br>
    <button type="button" onclick="addOption()" class="btn btn-success">+ Add choice</button>
    <button type="submit" value="Create" class="btn btn-primary">Create</button>
</form>
<script src="{% static 'polls/script.js' %}"></script>
{% endblock %}

polls/templates/polls/detail.html
{% extends 'base.html' %}
{% block content %}
<h2>{{ question.question_text }}</h2>
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
<input type="submit" value="Vote" class="vote_button">
</form>
{% endblock %}

polls/templates/polls/index.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h2 class="leftstr">Latest Polls</h2>
    <h2 class="rightstr"><a href="{% url 'polls:create' %}">Create New</a></h2>
</div>
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends 'base.html' %}
{% block content %}
<h2>{{ question.question_text }}</h2>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
<a href="{% url 'polls:index' %}">Or go Home?</a>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <meta charset="UTF-8">
    <title>{{ title }}</title>
</head>
<body>
    <div class="container">
        {% block content %} {% endblock %}
    </div>
</body>
</html>